source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'AR-Voice-Tutorial-iOS' do
    #anyRTC 音视频库
    pod 'ARtcKit_iOS', '~> 4.2.2.7'
    #anyRTC 实时消息库
    pod 'ARtmKit_iOS', '~> 1.0.2.0'
    
    pod 'SnapKit'
    pod 'IQKeyboardManager'
    pod 'SDWebImage', '~> 3.7.3'
    pod 'XHToast', '~> 1.4.0'
    pod 'TTTAttributedLabel'
    pod 'Bugly'
end

