platform :ios, '9.0'
use_frameworks!

target 'AR-Voice-Tutorial-iOS' do
    pod 'SnapKit'
    pod 'IQKeyboardManager'
    pod 'SDWebImage', '~> 3.7.3'
    pod 'XHToast', '~> 1.4.0'
    pod 'TTTAttributedLabel'
    pod 'Bugly'
end

